"""National Pest Directory — Flask app.

Server-rendered SEO directory over the scraped SQLite DB. Same playbook as
mobiledetailing.io: thousands of city/category/listing pages, sitemap, quote
form, AdSense slots. Unique long-form copy comes from the `content` table
(pre-generated by Gemini — see web/gen_content.py), never the live request.

Run:
    pip install flask
    python web/app.py            # http://127.0.0.1:5000
"""
import json
import math
import os
import re
import sqlite3
import sys
from datetime import date
from pathlib import Path

from flask import (Flask, abort, g, redirect, render_template, request,
                   url_for, Response, send_from_directory)

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scraper"))
import db as dbmod  # noqa: E402  (schema + slugify live here)

app = Flask(__name__)
app.config["SITE_NAME"] = "National Pest Directory"
# Canonical host for sitemap/canonicals/OG/JSON-LD. Override with env DOMAIN.
# Stored without a trailing slash, since every use appends an absolute path —
# rstrip so a DOMAIN set as ".../" can't produce "https://host//guides".
app.config["DOMAIN"] = os.environ.get(
    "DOMAIN", "https://nationalpestdirectory.com").rstrip("/")
app.config["ADSENSE_CLIENT"] = os.environ.get("ADSENSE_CLIENT", "")  # ca-pub-XXXX
app.config["GA_ID"] = os.environ.get("GA_ID", "")                    # G-XXXXXXXX
# Google Search Console verification token (the string in the meta-tag method).
app.config["GSC_VERIFICATION"] = os.environ.get("GSC_VERIFICATION", "")
# 24/7 call-tracking number for the homepage CTA. Override with env CTA_PHONE;
# set it empty to fall back to linking at /search instead of a tel: link.
app.config["CTA_PHONE"] = os.environ.get("CTA_PHONE", "+18663380533")

STATE_NAMES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
    "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming",
}

# Reading order for the ranked blocks on a city page: broadest, highest-intent
# service first, niche last. Deliberately NOT sorted by how many providers we
# scraped — in some metros that puts Wildlife Removal above General Pest Control
# on a page titled "best pest control". Anything not listed here sorts after,
# by provider count.
CATEGORY_ORDER = ("General Pest Control", "Exterminators", "Termite Control",
                  "Bed Bug Removal", "Rodent Control", "Mosquito Control",
                  "Wildlife Removal")

CATEGORY_ICONS = {
    "General Pest Control": "fa-bug",
    "Exterminators": "fa-spray-can-sparkles",
    "Termite Control": "fa-house-crack",
    "Bed Bug Removal": "fa-bed",
    "Rodent Control": "fa-otter",
    "Mosquito Control": "fa-mosquito",
    "Wildlife Removal": "fa-crow",
}


# ---------------------------------------------------------------- db helpers
def get_db():
    if "db" not in g:
        # read-only + immutable: serverless filesystems are read-only, and this
        # avoids SQLite creating -wal/-journal lock files next to the bundled DB.
        uri = f"file:{dbmod.DB_PATH.as_posix()}?mode=ro&immutable=1"
        g.db = sqlite3.connect(uri, uri=True)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_exc):
    d = g.pop("db", None)
    if d:
        d.close()


@app.after_request
def add_headers(resp):
    """Edge caching + baseline security headers."""
    if request.method == "GET" and resp.status_code == 200:
        resp.headers["Cache-Control"] = (
            "public, s-maxage=3600, stale-while-revalidate=86400")
    resp.headers["X-Content-Type-Options"] = "nosniff"
    resp.headers["X-Frame-Options"] = "SAMEORIGIN"
    resp.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    resp.headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=()"
    resp.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com "
        "https://pagead2.googlesyndication.com; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com "
        "https://cdnjs.cloudflare.com; "
        "font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; "
        "img-src 'self' data: https:; "
        "connect-src 'self' https:; frame-ancestors 'self'")
    return resp


def slugify(s):
    return dbmod.slugify(s or "")


def initials(name, n=2):
    """'Bulwark Exterminating' -> 'BE'. Monogram for a card with no logo."""
    words = [w for w in re.split(r"\W+", name or "") if w]
    if not words:
        return "?"
    if len(words) == 1:
        return words[0][:n].upper()
    return "".join(w[0] for w in words[:n]).upper()


def phone_display(raw):
    """+18663380533 -> (866) 338-0533. Non-US shapes pass through as-is."""
    digits = re.sub(r"\D", "", raw or "")
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    if len(digits) != 10:
        return raw or ""
    return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"


# Closed/gone businesses stay in the DB for audit but must never reach a page.
# Every listings query below carries this filter — see scraper/scrape.py.
LIVE = dbmod.ACTIVE


# make these usable inside macros (which don't inherit context processors)
app.jinja_env.filters["slugify"] = slugify
app.jinja_env.filters["initials"] = initials


def content_for(key):
    """Fetch cached Gemini copy, or None. {intro, faq:[{q,a}]}."""
    row = get_db().execute(
        "SELECT intro, faq FROM content WHERE key = ?", (key,)
    ).fetchone()
    if not row:
        return None
    return {"intro": row["intro"],
            "faq": json.loads(row["faq"]) if row["faq"] else []}


# ---------------------------------------------------------------- context
@app.context_processor
def inject_globals():
    cats = [r["category"] for r in get_db().execute(
        f"SELECT DISTINCT category FROM listings WHERE category IS NOT NULL "
        f"AND {LIVE} ORDER BY category")]
    return {
        "SITE_NAME": app.config["SITE_NAME"],
        "ALL_CATEGORIES": cats,
        "CATEGORY_ICONS": CATEGORY_ICONS,
        "ADSENSE_CLIENT": app.config["ADSENSE_CLIENT"],
        "GA_ID": app.config["GA_ID"],
        "DOMAIN": app.config["DOMAIN"],
        "GSC_VERIFICATION": app.config["GSC_VERIFICATION"],
        "CTA_PHONE": app.config["CTA_PHONE"],
        "CTA_PHONE_DISPLAY": phone_display(app.config["CTA_PHONE"]),
        "STATE_NAMES": STATE_NAMES,
        "cat_slug": slugify,
    }


# ---------------------------------------------------------------- routes
@app.route("/")
def home():
    d = get_db()
    sort = request.args.get("sort", "reviews")
    order = {"reviews": "reviews DESC", "rating": "rating DESC, reviews DESC",
             "name": "name ASC"}.get(sort, "reviews DESC")
    listings = d.execute(
        f"SELECT * FROM listings WHERE {LIVE} ORDER BY {order} LIMIT 24").fetchall()
    cities = d.execute(
        f"SELECT city, state, COUNT(*) n FROM listings WHERE {LIVE} "
        f"GROUP BY city, state ORDER BY n DESC LIMIT 24").fetchall()
    cats = d.execute(
        f"SELECT category, COUNT(*) n FROM listings "
        f"WHERE category IS NOT NULL AND {LIVE} "
        f"GROUP BY category ORDER BY n DESC").fetchall()
    total = dbmod.count(d)
    return render_template("index.html", listings=listings, cities=cities,
                           cats=cats, total=total, sort=sort)


# NOTE: /listing/<slug> was retired. A detail page held one scraped row and no
# unique value over the city page's ranked card, so it was thin content with a
# crawl cost of one URL per listing (~24k). City pages are the leaf now; a card's
# secondary link goes to the provider's own site.

PER_PAGE = 24


def _page():
    try:
        return max(1, int(request.args.get("page", 1)))
    except ValueError:
        return 1


def _pageinfo(page, total):
    pages = max(1, (total + PER_PAGE - 1) // PER_PAGE)
    return {"page": page, "pages": pages,
            "has_prev": page > 1, "has_next": page < pages}


@app.route("/category/<slug>")
def category(slug):
    d = get_db()
    cats = {slugify(r["category"]): r["category"] for r in d.execute(
        f"SELECT DISTINCT category FROM listings "
        f"WHERE category IS NOT NULL AND {LIVE}")}
    name = cats.get(slug)
    if not name:
        abort(404)
    page = _page()
    total = d.execute(
        f"SELECT COUNT(*) FROM listings WHERE category = ? AND {LIVE}",
        (name,)).fetchone()[0]
    rows = d.execute(
        f"SELECT * FROM listings WHERE category = ? AND {LIVE} "
        f"ORDER BY reviews DESC LIMIT ? OFFSET ?",
        (name, PER_PAGE, (page - 1) * PER_PAGE)).fetchall()
    copy = content_for(f"category:{slug}")
    stats = d.execute(
        f"SELECT ROUND(AVG(rating),1) avg, COUNT(DISTINCT city||state) cities, "
        f"SUM(reviews) revs FROM listings "
        f"WHERE category = ? AND rating IS NOT NULL AND {LIVE}",
        (name,)).fetchone()
    top_cities = d.execute(
        f"SELECT city, state, COUNT(*) n FROM listings "
        f"WHERE category = ? AND {LIVE} "
        f"GROUP BY city, state ORDER BY n DESC LIMIT 5", (name,)).fetchall()
    facts = {"avg": stats["avg"], "cities": stats["cities"],
             "reviews": stats["revs"] or 0, "top_cities": top_cities}
    return render_template("category.html", name=name, slug=slug, rows=rows,
                           total=total, copy=copy, pg=_pageinfo(page, total),
                           facts=facts, base_url=f"/category/{slug}")


# A city page shows one ranked block per service category. Categories with more
# providers than this get a "see all" link into /search rather than a longer
# list — past ~6 the marginal card earns no clicks and just costs mobile fold.
PER_CATEGORY = 6
NEARBY_CITIES = 10

_CENTROIDS = None


def _city_centroids():
    """[(city, state, lat, lng)] for every city we list, cached for the process.

    ~1k cities over 24k listings: one aggregate query, held for the life of the
    worker, so the nearby-cities block costs arithmetic instead of a table scan
    on every city pageview. The DB is opened read-only + immutable, so it cannot
    go stale under us mid-process.
    """
    global _CENTROIDS
    if _CENTROIDS is None:
        _CENTROIDS = [
            (r["city"], r["state"], r["lat"], r["lng"])
            for r in get_db().execute(
                f"SELECT city, state, AVG(lat) lat, AVG(lng) lng FROM listings "
                f"WHERE lat IS NOT NULL AND lng IS NOT NULL AND {LIVE} "
                f"GROUP BY city, state")]
    return _CENTROIDS


def _nearby_cities(city_, state_, limit=NEARBY_CITIES):
    """The closest other cities we have pages for — any state, since a metro's
    real neighbours cross state lines (Charlotte NC -> Rock Hill SC).

    Equirectangular approximation: at the scale of "cities within a metro" the
    error against great-circle distance is far below the gap between ranks, and
    it avoids a trig call per city.
    """
    rows = _city_centroids()
    here = next((r for r in rows if r[0] == city_ and r[1] == state_), None)
    if not here:
        return []
    lat0, lng0 = here[2], here[3]
    coslat = math.cos(math.radians(lat0))
    out = []
    for c, st, lat, lng in rows:
        if c == city_ and st == state_:
            continue
        dy, dx = lat - lat0, (lng - lng0) * coslat
        out.append((dx * dx + dy * dy, c, st))
    out.sort()
    return [{"city": c, "state": st} for _, c, st in out[:limit]]


@app.route("/<state>/<cityslug>")
def city(state, cityslug):
    state = state.upper()
    d = get_db()
    # match by slug of city (filter in Python since slugify isn't in SQL)
    allrows = d.execute(
        f"SELECT * FROM listings WHERE state = ? AND {LIVE} "
        f"ORDER BY reviews DESC", (state,)).fetchall()
    rows = [r for r in allrows if slugify(r["city"]) == cityslug]
    if not rows:
        abort(404)
    cname = rows[0]["city"]
    copy = content_for(f"city:{cityslug}-{state.lower()}")

    # One ranked block per service, in CATEGORY_ORDER. `rows` is already
    # review-DESC, so each block inherits that order — the ranking the page
    # claims. Uncategorised listings have no block but still count as providers.
    buckets = {}
    for r in rows:
        if r["category"]:
            buckets.setdefault(r["category"], []).append(r)

    def rank(kv):
        name, rs = kv
        idx = CATEGORY_ORDER.index(name) if name in CATEGORY_ORDER else None
        return (0, idx, 0) if idx is not None else (1, 0, -len(rs))

    groups = [{"name": c, "slug": slugify(c), "rows": rs[:PER_CATEGORY],
               "total": len(rs)}
              for c, rs in sorted(buckets.items(), key=rank)]

    rated = [r["rating"] for r in rows if r["rating"] is not None]
    facts = {"providers": len(rows),
             "avg": round(sum(rated) / len(rated), 1) if rated else None,
             "reviews": sum(r["reviews"] or 0 for r in rows),
             "services": len(groups),
             "shown": sum(len(g["rows"]) for g in groups)}
    return render_template("city.html", city=cname, state=state, groups=groups,
                           facts=facts, copy=copy,
                           nearby=_nearby_cities(cname, state),
                           updated=date.today().strftime("%B %Y"))


@app.route("/state/<st>")
def state(st):
    st = st.upper()
    if st not in STATE_NAMES:
        abort(404)
    d = get_db()
    cities_ = d.execute(
        f"SELECT city, COUNT(*) n FROM listings WHERE state = ? AND {LIVE} "
        f"GROUP BY city ORDER BY n DESC", (st,)).fetchall()
    if not cities_:
        abort(404)
    total = d.execute(
        f"SELECT COUNT(*) FROM listings WHERE state = ? AND {LIVE}",
        (st,)).fetchone()[0]
    top = d.execute(
        f"SELECT * FROM listings WHERE state = ? AND {LIVE} "
        f"ORDER BY reviews DESC LIMIT 12", (st,)).fetchall()
    return render_template("state.html", st=st, name=STATE_NAMES[st],
                           cities=cities_, total=total, top=top)


@app.route("/cities")
def cities():
    # group by state -> lighter page + links to state hubs
    rows = get_db().execute(
        f"SELECT state, COUNT(DISTINCT city) c, COUNT(*) n FROM listings "
        f"WHERE {LIVE} GROUP BY state ORDER BY n DESC").fetchall()
    return render_template("cities.html", rows=rows)


@app.route("/categories")
def categories():
    rows = get_db().execute(
        f"SELECT category, COUNT(*) n FROM listings "
        f"WHERE category IS NOT NULL AND {LIVE} "
        f"GROUP BY category ORDER BY n DESC").fetchall()
    return render_template("categories.html", rows=rows)


# Guides are hand-authored long-form content, imported by
# scripts/import_guides.py into metadata (web/guides/<slug>.json) plus a prose
# partial (templates/guides/<slug>.html) that guide.html renders on base.html.
GUIDES_DIR = Path(__file__).resolve().parent / "guides"


def _load_guides():
    """{slug: metadata} for the articles, plus the hub. Read once at import —
    this is deploy-time content, and the serverless filesystem is read-only."""
    articles, hub = {}, None
    for f in sorted(GUIDES_DIR.glob("*.json")):
        data = json.loads(f.read_text(encoding="utf-8"))
        if f.stem == "_hub":
            hub = data
        else:
            articles[f.stem] = data
    return articles, hub


GUIDES, GUIDES_HUB = _load_guides()
# Whitelist for <slug>, so a request can never reach an arbitrary template.
GUIDE_SLUGS = frozenset(GUIDES)


def _jsonld(nodes, path):
    """Authored JSON-LD -> one @graph, with __DOMAIN__ resolved and a
    BreadcrumbList (which the importer strips) rebuilt for this URL."""
    base = app.config["DOMAIN"]
    crumbs = [("Home", "/"), ("Guides", "/guides")]
    if path != "/guides":
        crumbs.append((GUIDES[path.rsplit("/", 1)[1]]["title"], path))
    graph = list(nodes) + [{
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i, "name": name,
             "item": base + url}
            for i, (name, url) in enumerate(crumbs, 1)],
    }]
    doc = {"@context": "https://schema.org", "@graph": graph}
    return json.dumps(doc, ensure_ascii=False).replace("__DOMAIN__", base)


@app.route("/guides")
def guides():
    return render_template("guides.html", hub=GUIDES_HUB,
                           jsonld=_jsonld(GUIDES_HUB["jsonld"], "/guides"))


@app.route("/guides/<slug>")
def guide(slug):
    if slug not in GUIDE_SLUGS:
        abort(404)
    g_ = GUIDES[slug]
    return render_template("guide.html", guide=g_,
                           jsonld=_jsonld(g_["jsonld"], f"/guides/{slug}"))


# abbrev + full-name -> 2-letter code, for parsing "City, State" input.
_STATE_LOOKUP = {abbr.lower(): abbr for abbr in STATE_NAMES}
_STATE_LOOKUP.update({name.lower(): abbr for abbr, name in STATE_NAMES.items()})


def _parse_location(loc):
    """Turn a free-text location into a precise SQL fragment + args.

    Supports (in priority order):
      * ZIP code (5 digits, optional +4) -> matches the zip inside `address`.
      * "City, State" -> exact city + state, so Springfield IL never matches
        Springfield MO.
      * bare text -> loose fallback (city or state contains the text).
    """
    zip_match = re.fullmatch(r"(\d{5})(?:-\d{4})?", loc)
    if zip_match:
        z = zip_match.group(1)
        # zip is a standalone token in the address ("..., NY 10023"); the
        # leading space avoids matching 5-digit street numbers.
        return " AND address LIKE ?", [f"% {z}%"]
    if "," in loc:
        city_part, _, state_part = loc.rpartition(",")
        city_part = city_part.strip()
        abbr = _STATE_LOOKUP.get(state_part.strip().lower())
        if city_part and abbr:
            return " AND city = ? AND state = ?", [city_part, abbr]
    # bare state name/abbrev -> filter by state only
    abbr = _STATE_LOOKUP.get(loc.lower())
    if abbr:
        return " AND state = ?", [abbr]
    return " AND (city LIKE ? OR state LIKE ?)", [f"%{loc}%", f"%{loc}%"]


@app.route("/search")
def search():
    from urllib.parse import urlencode
    q = (request.args.get("q") or "").strip()
    cat = (request.args.get("category") or "").strip()
    loc = (request.args.get("city") or "").strip()
    where = f"WHERE {LIVE}"
    args = []
    if q:
        where += " AND (name LIKE ? OR city LIKE ?)"
        args += [f"%{q}%", f"%{q}%"]
    if cat:
        where += " AND category = ?"
        args.append(cat)
    if loc:
        frag, frag_args = _parse_location(loc)
        where += frag
        args += frag_args
    d = get_db()
    total = d.execute(f"SELECT COUNT(*) FROM listings {where}", args).fetchone()[0]
    page = _page()
    rows = d.execute(
        f"SELECT * FROM listings {where} ORDER BY reviews DESC LIMIT ? OFFSET ?",
        args + [PER_PAGE, (page - 1) * PER_PAGE]).fetchall()
    qs = urlencode({k: v for k, v in
                    (("q", q), ("category", cat), ("city", loc)) if v})
    base_url = "/search?" + qs if qs else "/search"
    return render_template("search.html", rows=rows, q=q, cat=cat, loc=loc,
                           total=total, pg=_pageinfo(page, total),
                           base_url=base_url)


# ---------------------------------------------------------------- SEO
@app.route("/sitemap.xml")
def sitemap():
    d = get_db()
    base = app.config["DOMAIN"]
    today = date.today().isoformat()
    # (loc, priority, changefreq)
    urls = [(base + "/", "1.0", "daily"),
            (base + "/search", "0.5", "weekly"),
            (base + "/cities", "0.7", "weekly"),
            (base + "/categories", "0.7", "weekly")]
    for r in d.execute(f"SELECT DISTINCT category FROM listings "
                       f"WHERE category IS NOT NULL AND {LIVE}"):
        urls.append((f"{base}/category/{slugify(r['category'])}", "0.8", "weekly"))
    urls.append((base + "/guides", "0.7", "weekly"))
    for slug in sorted(GUIDE_SLUGS):
        urls.append((f"{base}/guides/{slug}", "0.7", "monthly"))
    for r in d.execute(f"SELECT DISTINCT state FROM listings WHERE {LIVE}"):
        urls.append((f"{base}/state/{r['state'].lower()}", "0.7", "weekly"))
    for r in d.execute(f"SELECT DISTINCT city, state FROM listings WHERE {LIVE}"):
        urls.append((f"{base}/{r['state'].lower()}/{slugify(r['city'])}",
                     "0.8", "weekly"))
    # No per-listing URLs: /listing/<slug> was retired (see the city route).
    xml = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, pri, cf in urls:
        xml.append(f"<url><loc>{loc}</loc><lastmod>{today}</lastmod>"
                   f"<changefreq>{cf}</changefreq><priority>{pri}</priority></url>")
    xml.append("</urlset>")
    return Response("\n".join(xml), mimetype="application/xml")


@app.route("/favicon.ico")
def favicon():
    # Google's favicon crawler checks the site root by convention.
    return send_from_directory(app.static_folder, "favicon.ico",
                               mimetype="image/x-icon")


@app.route("/robots.txt")
def robots():
    txt = (f"User-agent: *\nAllow: /\n"
           f"Sitemap: {app.config['DOMAIN']}/sitemap.xml\n")
    return Response(txt, mimetype="text/plain")


@app.errorhandler(404)
def not_found(_e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    app.run(debug=True, port=5000)
